# Generated by Django 5.1.4 on 2026-05-11 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=160)),
                ('target', models.CharField(max_length=180)),
                ('tone', models.CharField(default='success', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('telegram', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('volume', models.CharField(default='₹0', max_length=40)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='crm.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120)),
                ('holder_name', models.CharField(max_length=160)),
                ('account_number', models.CharField(max_length=80)),
                ('ifsc', models.CharField(max_length=20)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('account_type', models.CharField(default='Current', max_length=40)),
                ('upi_id', models.CharField(blank=True, max_length=120)),
                ('upi_app', models.CharField(blank=True, max_length=60)),
                ('upi_mobile', models.CharField(blank=True, max_length=40)),
                ('customer_id', models.CharField(blank=True, max_length=120)),
                ('user_id', models.CharField(blank=True, max_length=120)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('transaction_password', models.CharField(blank=True, max_length=200)),
                ('mpin', models.CharField(blank=True, max_length=40)),
                ('tpin', models.CharField(blank=True, max_length=40)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_usage', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('registered_mobile', models.CharField(blank=True, max_length=40)),
                ('recovery_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('login_url', models.URLField(blank=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='crm.agent')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='crm.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Merchant', 'Merchant')], max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('telegram', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
