# Generated by Django 5.1.4 on 2026-05-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bank_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="beneficiary_time_limit",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
